### PR TITLE
Add OAuth2 support

### PR DESCRIPTION
**Pull request by downtownallday**
Add an OAuth2 authorization server and allow Roundcube users to authenticate using with passwords and TOTP.  Most mail user agents do not support IMAP/XOAUTH2, so standard IMAP PLAIN authentication isn't going away just yet. Roundcube is adding support, so this PR will aim to support that. Thunderbird does not yet support XOAUTH2 for anything but gmail, and K9 has no support. However, over time these applications will likely get updated, and perhaps PLAIN authentication could be disabled entirely.

### CODE REVIEW

**Comment by downtownallday** [comment]
Roundcube oauth support on master has been broken for quite a while as the maintainers shifted to adding support for php 8

**Comment by downtownallday** [comment]
Filed a dovecot bug (XR 148)

**Comment by downtownallday** [comment]
There is still some critical missing support in third party applications to get this working in a way that's usable. The list so far:

- [x] Dovecot support (version 2.3+ required)
- [x] Roundcube support (for general login) (version 1.5+ required)
- [ ] Thunderbird support see: https://bugzilla.mozilla.org/show_bug.cgi?id=1602166
- [ ] K9 support see: https://github.com/k9mail/k-9/issues?q=is%3Aissue+is%3Aopen+oauth
- [ ] iphone mail support
- [ ] Nextcloud support (for general login and Roundcube carddav support)
- [x] Roundcube carddav plugin support (contact sync with Nextcloud) (version 4.2.2+ required)
- [ ] Roundcube Persistent login plugin support (not critical)

**Comment by downtownallday** [comment]
I am giving up on this for now.

**Comment by dumblob** [comment]
You made a lot of progress and spent lots of time with this. I think it is worth coming back to this later as oauth2 will stay with us for many years IMHO.

**Pull request closed without merging**
